# Generated by Django 4.1.7 on 2023-03-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PH', 'Phone'), ('TAB', 'Tablet'), ('LT', 'Laptop')], max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('APR', 'Approved'), ('OUT', 'Handed Out'), ('REJ', 'Rejected'), ('RET', 'Returned')], default='REQ', max_length=3)),
                ('checkout_condition', models.CharField(blank=True, choices=[('OK', 'WORKING'), ('NR', 'NEEDS REPAIR')], max_length=2, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('OK', 'WORKING'), ('NR', 'NEEDS REPAIR')], max_length=3, null=True)),
                ('requested_checkout_date', models.DateTimeField()),
                ('requested_return_date', models.DateTimeField()),
                ('actual_checkout_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gadgets.device')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requested', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requisition_reviewed', to='accounts.employee')),
            ],
        ),
    ]
